import { Profile, Service, ResumeItem, PortfolioProject, Competency, SkillCategory } from "@/types";

export const initialProfile: Profile = {
  greeting: "HALO, SAYA",
  namePrefix: "I'M",
  fullName: "Adha Dwi Fathur.r",
  highlightWords: "Fathur.r",
  roleBadges: ["MAHASISWA TEKNIK TELEKOMUNIKASI", "IOT & NETWORKING"],
  bio: "Saya adalah mahasiswa Teknik Telekomunikasi di Politeknik Negeri Semarang dengan fokus pada jaringan komputer, telekomunikasi, dan sistem perangkat keras IoT.",
  heroDescription: "Mahasiswa Teknik Telekomunikasi di Politeknik Negeri Semarang. Berhasrat tinggi dalam mengembangkan solusi teknologi inovatif dengan fokus kuat pada jaringan komputer, telekomunikasi, rekayasa perangkat keras IoT, dan transformasi digital.",
  avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=600",
  heroImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800",
  stats: {
    yearsExp: 3,
    projectsDone: 25,
    happyClients: 20,
    followers: 850,
  },
  contactInfo: {
    email: "dfadha1923@gmail.com",
    phone: "",
    location: "Semarang, Jawa Tengah, Indonesia",
    github: "https://github.com",
    linkedin: "https://www.linkedin.com/in/adha-dwi-fathurrochman-670a87297/",
    instagram: "https://www.instagram.com/adhafathurrchm.iwd/",
    twitter: "https://twitter.com",
  },
};

export const initialServices: Service[] = [
  {
    id: "serv-1",
    title: "Jaringan Komputer & Telekomunikasi",
    description: "Merancang, mengonfigurasi, dan memelihara jaringan komputer, protokol routing & switching, serta sistem telekomunikasi.",
    iconName: "Network",
    order: 1,
  },
  {
    id: "serv-2",
    title: "IoT & Rekayasa Perangkat Keras",
    description: "Merancang dan merakit perangkat IoT, pengkabelan mikrokontroler (ESP32/Arduino), dan sistem otomasi cerdas.",
    iconName: "Server",
    order: 2,
  },
  {
    id: "serv-3",
    title: "Lomba & Inovasi Teknologi",
    description: "Aktif mengikuti kompetisi tingkat nasional di bidang esai ilmiah, rekayasa IoT, jaringan komputer, dan inovasi teknologi.",
    iconName: "Award",
    order: 3,
  },
  {
    id: "serv-4",
    title: "Desain Grafis & Media Sosial",
    description: "Membuat konten grafis digital, promosi media sosial, spanduk, dan materi branding cetak.",
    iconName: "Layout",
    order: 4,
  },
];

export const initialCompetencies: Competency[] = [
  {
    id: "comp-1",
    title: "Sertifikat Keahlian Network Technician & Cyber Security",
    issuer: "Diskominfo & LSK Teknologi",
    issueDate: "2024",
    category: "Networking",
    imageUrl: "https://images.unsplash.com/photo-1589330694653-ded6df03f754?auto=format&fit=crop&q=80&w=800",
    credentialUrl: "https://drive.google.com",
    description: "Sertifikat resmi kompetensi dalam konfigurasi perangkat jaringan, routing & switching, manajemen VLAN, IP subnetting, serta instalasi dan pengamanan infrastruktur jaringan komputer.",
    order: 1,
  },
  {
    id: "comp-2",
    title: "Sertifikat Keahlian IoT Engineering & Smart Automation",
    issuer: "Elektro Expo & POLIREVO",
    issueDate: "2024",
    category: "IoT & Embedded",
    imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=800",
    credentialUrl: "https://drive.google.com",
    description: "Sertifikat kompetensi perakitan perangkat IoT, wiring mikrokontroler (ESP32/Arduino), komunikasi protokol MQTT, integrasi sensor cerdas, dan sistem otomasi.",
    order: 2,
  },
  {
    id: "comp-3",
    title: "Sertifikat Kompetensi Sistem Telekomunikasi & Fiber Optics",
    issuer: "Politeknik Negeri Semarang",
    issueDate: "2024",
    category: "Telecommunication",
    imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800",
    credentialUrl: "https://drive.google.com",
    description: "Sertifikat keahlian bidang sistem transmisi telekomunikasi, serat optik (splicing & pengukuran OTDR), serta prinsip kerja transmisi jaringan nirkabel.",
    order: 3,
  },
];

export const initialResumeItems: ResumeItem[] = [
  // Education
  {
    id: "res-edu-1",
    category: "EDUCATION",
    title: "Politeknik Negeri Semarang",
    subtitle: "Mahasiswa Teknik Telekomunikasi",
    period: "2024 - Sekarang",
    description: "Mahasiswa D3/D4 Teknik Telekomunikasi. Aktif mengikuti kompetisi teknologi nasional dan organisasi mahasiswa/robotika.",
    order: 1,
  },
  {
    id: "res-edu-2",
    category: "EDUCATION",
    title: "SMK Negeri 2 Sragen",
    subtitle: "Pendidikan Menengah Kejuruan",
    period: "2021 - 2024",
    description: "Aktif dalam kepemimpinan OSIS dan kompetisi akademik kejuruan.",
    order: 2,
  },
  {
    id: "res-edu-3",
    category: "EDUCATION",
    title: "SMP Negeri 2 Gondang, Sragen",
    subtitle: "Pendidikan Menengah Pertama",
    period: "2018 - 2021",
    description: "Konsisten meraih peringkat 5 besar paralel kelas selama 3 tahun berturut-turut.",
    order: 3,
  },

  // Experience
  {
    id: "res-exp-1",
    category: "EXPERIENCE",
    title: "IoT Engineer",
    subtitle: "Office FO",
    period: "2023 - Sekarang",
    description: "Membantu perakitan perangkat keras IoT, mikrokontroler, dan wiring perangkat.",
    order: 1,
  },
  {
    id: "res-exp-2",
    category: "EXPERIENCE",
    title: "Desainer Media Sosial",
    subtitle: "Batik Hamayra",
    period: "Feb 2024 - Mei 2024",
    description: "Desainer lepas pembuat konten promosi digital dan branding media sosial.",
    order: 2,
  },
  {
    id: "res-exp-3",
    category: "EXPERIENCE",
    title: "Desainer Grafis",
    subtitle: "Faster Digital Print",
    period: "2021 - 2024",
    description: "Desainer lepas merancang spanduk, media cetak, dan materi branding perusahaan.",
    order: 3,
  },
  {
    id: "res-exp-4",
    category: "EXPERIENCE",
    title: "Teknisi Jaringan",
    subtitle: "Diskominfo Kab. Sragen",
    period: "Nov 2022 - Feb 2023",
    description: "Magang teknisi jaringan memelihara infrastruktur jaringan daerah dan peralatan server pemkab.",
    order: 4,
  },

  // Organization (With Photos/Logos)
  {
    id: "res-org-1",
    category: "ORGANIZATION",
    title: "Ketua Umum",
    subtitle: "Keluarga Mahasiswa Sragen Polines (KMS)",
    period: "2024 - Sekarang",
    description: "Memimpin organisasi daerah mahasiswa Sragen di Politeknik Negeri Semarang.",
    imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=400",
    order: 1,
  },
  {
    id: "res-org-2",
    category: "ORGANIZATION",
    title: "Wakil Ketua Umum",
    subtitle: "Polines Robotics Evolution (POLIREVO)",
    period: "2025 - Sekarang",
    description: "Mengelola tim riset robotika dan inovasi teknologi mahasiswa.",
    imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=400",
    order: 2,
  },
  {
    id: "res-org-3",
    category: "ORGANIZATION",
    title: "IoT Engineer",
    subtitle: "Office FO",
    period: "2023 - Sekarang",
    description: "Pengembangan teknis perangkat keras dan perakitan wiring IoT.",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400",
    order: 3,
  },
  {
    id: "res-org-4",
    category: "ORGANIZATION",
    title: "Ketua II",
    subtitle: "OSIS SMKN 2 Sragen",
    period: "2023 - 2024",
    description: "Menyelenggarakan program siswa, pelatihan kepemimpinan, dan kegiatan sekolah.",
    imageUrl: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=400",
    order: 4,
  },
  {
    id: "res-org-5",
    category: "ORGANIZATION",
    title: "Ketua II",
    subtitle: "Forum OSIS Kab. Sragen (FOSRA)",
    period: "2023 - 2024",
    description: "Mengordinasikan pengurus OSIS tingkat SMA/SMK se-Kabupaten Sragen.",
    imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=400",
    order: 5,
  },
  {
    id: "res-org-6",
    category: "ORGANIZATION",
    title: "Sekretaris",
    subtitle: "Dewan Ambalan Penegak SMKN 2 Sragen",
    period: "2023 - 2024",
    description: "Mengelola administrasi, kegiatan kepramukaan, dan acara Ambalan.",
    imageUrl: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&q=80&w=400",
    order: 6,
  },

  // Award (With Photos)
  {
    id: "res-awd-1",
    category: "AWARD",
    title: "Juara 1 — Video Iklan Layanan Masyarakat",
    subtitle: "Iklan Layanan Masyarakat Kab. Sragen 2024",
    period: "2024",
    description: "Meraih Juara 1 dalam kompetisi video Iklan Layanan Masyarakat.",
    imageUrl: "https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?auto=format&fit=crop&q=80&w=400",
    order: 1,
  },
  {
    id: "res-awd-2",
    category: "AWARD",
    title: "Juara 2 — Cyber Security Competition",
    subtitle: "Cyber Security Competition Kab. Sragen 2024",
    period: "2024",
    description: "Meraih Juara 2 kompetisi keamanan siber tingkat kabupaten.",
    imageUrl: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=400",
    order: 2,
  },
  {
    id: "res-awd-3",
    category: "AWARD",
    title: "Juara 2 — Lomba Baris Berbaris",
    subtitle: "Lomba Baris Berbaris Kab. Sragen 2024",
    period: "2024",
    description: "Meraih Juara 2 lomba baris berbaris tingkat kabupaten.",
    imageUrl: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=400",
    order: 3,
  },
  {
    id: "res-awd-4",
    category: "AWARD",
    title: "Top 10 Finalis — IoT Competition",
    subtitle: "Elektro Expo - IoT Competition 2024",
    period: "2024",
    description: "Terpilih sebagai Top 10 finalis kompetisi inovasi IoT nasional Elektro Expo.",
    imageUrl: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&q=80&w=400",
    order: 4,
  },
];

export const initialProjects: PortfolioProject[] = [
  {
    id: "proj-1",
    title: "Perakitan Perangkat Keras IoT & Otomasi Cerdas",
    category: "IOT",
    thumbnailUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=800",
    description: "Perakitan mikrokontroler IoT, wiring sensor, dan sistem otomasi cerdas untuk Office FO.",
    projectUrl: "https://adhafathur.my.id",
    featured: true,
    createdAt: Date.now() - 1000000,
  },
  {
    id: "proj-2",
    title: "Infrastruktur Jaringan & Pemeliharaan Server Diskominfo",
    category: "NETWORKING",
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800",
    description: "Konfigurasi router, VLAN, IP subnetting, dan troubleshooting teknisi jaringan.",
    projectUrl: "https://adhafathur.my.id",
    featured: true,
    createdAt: Date.now() - 2000000,
  },
  {
    id: "proj-3",
    title: "Proyek Desain Grafis & Media Promosi Digital",
    category: "OTHER",
    thumbnailUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=800",
    description: "Spanduk promosi digital, materi pemasaran media sosial, dan desain branding untuk Batik Hamayra & Faster Digital Print.",
    projectUrl: "https://adhafathur.my.id",
    featured: true,
    createdAt: Date.now() - 3000000,
  },
];

export const initialSkills: SkillCategory[] = [
  {
    id: "skill-1",
    title: "Jaringan & Telekomunikasi",
    subtitle: "Kompetensi Utama",
    iconName: "Network",
    skills: ["Cisco & MikroTik", "VLAN & IP Subnetting", "Routing & Switching", "Fiber Optic & OTDR", "Cyber Security Basics"],
    order: 1,
  },
  {
    id: "skill-2",
    title: "IoT & Embedded Systems",
    subtitle: "Hardware & Otomasi",
    iconName: "Server",
    skills: ["ESP32 / ESP8266", "Arduino Wiring", "Protokol MQTT", "Sensor Integration", "Smart Automation"],
    order: 2,
  },
  {
    id: "skill-3",
    title: "Desain Grafis & Media",
    subtitle: "Kreatif & Visual",
    iconName: "Layout",
    skills: ["Canva & Photoshop", "Spanduk & Banner Cetak", "Konten Media Sosial", "Branding Digital"],
    order: 3,
  },
  {
    id: "skill-4",
    title: "Bahasa & Perangkat Lunak",
    subtitle: "Programming & Tools",
    iconName: "Code",
    skills: ["C / C++", "HTML5 / CSS3", "JavaScript Basics", "Linux Environment", "Git & GitHub"],
    order: 4,
  },
];
